LIFE EXPECTANCY PROJECT


CREATE DATABASE life_expectancy;
USE life_expectancy;
CREATE TABLE life_exp(
DIME_TIME INT,
GEO_NAME_SHORT VARCHAR(100),
DIM_SEX VARCHAR(10),
AMOUNT_N DECIMAL(5,2)
);
--Overall highest and lowest life expectancy
SELECT GEO_NAME_SHORT, DIM_SEX, DIME_TIME, AMOUNT_N
FROM life_exp
ORDER BY AMOUNT_N DESC
LIMIT 1;
SELECT GEO_NAME_SHORT, DIM_SEX, DIME_TIME, AMOUNT_N
FROM life_exp
ORDER BY AMOUNT_N ASC
LIMIT 1;

--Yearwise Highest and Lowest life expectancy
SELECT DIME_TIME, GEO_NAME_SHORT, DIM_SEX, AMOUNT_N
FROM (SELECT DIME_TIME, GEO_NAME_SHORT, DIM_SEX, AMOUNT_N,
RANK() OVER (PARTITION BY DIME_TIME ORDER BY AMOUNT_N DESC) AS rnk
FROM life_exp) ranked
WHERE rnk=1;
SELECT DIME_TIME, GEO_NAME_SHORT, DIM_SEX, AMOUNT_N
FROM (SELECT DIME_TIME, GEO_NAME_SHORT, DIM_SEX, AMOUNT_N,
RANK() OVER (PARTITION BY DIME_TIME ORDER BY AMOUNT_N ASC) AS rnk
FROM life_exp) ranked
WHERE rnk=1;

--Top 10 Countries(Highest and lowest avg life expectancy)
SELECT GEO_NAME_SHORT, AVG(AMOUNT_N) AS avg_expectancy
FROM life_exp
GROUP BY GEO_NAME_SHORT
ORDER BY avg_expectancy DESC
LIMIT 10;
SELECT GEO_NAME_SHORT, AVG(AMOUNT_N) AS avg_expectancy
FROM life_exp
GROUP BY GEO_NAME_SHORT
ORDER BY avg_expectancy ASC
LIMIT 10;

--Gender comparison overall
SELECT DIM_SEX, AVG(AMOUNT_N) AS avg_expectancy
FROM life_exp
GROUP BY DIM_SEX
ORDER BY avg_expectancy DESC;

--Gender lead by country (all years)
SELECT GEO_NAME_SHORT, DIM_SEX, AVG(AMOUNT_N) AS avg_expectancy
FROM life_exp
GROUP BY GEO_NAME_SHORT, DIM_SEX
ORDER BY GEO_NAME_SHORT, avg_expectancy DESC;

--Trend analysis overtime (countrywise)
SELECT DIME_TIME, GEO_NAME_SHORT, AVG(AMOUNT_N) AS avg_expectancy
FROM life_exp
GROUP BY DIME_TIME, GEO_NAME_SHORT
ORDER BY GEO_NAME_SHORT, DIME_TIME;

--Gender gap analysis
SELECT GEO_NAME_SHORT,
       MAX(CASE WHEN DIM_SEX = 'Female' THEN AMOUNT_N END) AS female_expectancy,
       MAX(CASE WHEN DIM_SEX = 'Male' THEN AMOUNT_N END) AS male_expectancy,
       MAX(CASE WHEN DIM_SEX = 'Female' THEN AMOUNT_N END) -
       MAX(CASE WHEN DIM_SEX = 'Male' THEN AMOUNT_N END) AS gender_gap
FROM life_exp
GROUP BY GEO_NAME_SHORT
ORDER BY gender_gap DESC;

-- Year-on-Year Change 
SELECT GEO_NAME_SHORT, DIM_SEX, DIME_TIME, 
AMOUNT_N - LAG(AMOUNT_N) OVER (PARTITION BY GEO_NAME_SHORT, DIM_SEX ORDER BY DIME_TIME) AS chng
FROM life_exp;

-- Global Average vs Country (Benchmarking)
SELECT DIME_TIME, GEO_NAME_SHORT,AVG(AMOUNT_N) AS COUNTRY_AVG,
(SELECT AVG(AMOUNT_N) FROM life_exp WHERE DIME_TIME = DIME_TIME) AS global_avg
FROM life_exp
GROUP BY DIME_TIME, GEO_NAME_SHORT;

-- Top Country's Best and Worst Year (with gender)
SELECT GEO_NAME_SHORT, DIME_TIME, DIM_SEX, AMOUNT_N
FROM life_exp
WHERE GEO_NAME_SHORT = (
    SELECT GEO_NAME_SHORT
    FROM life_exp
    GROUP BY GEO_NAME_SHORT
    ORDER BY AVG(AMOUNT_N) DESC
    LIMIT 1
)
ORDER BY AMOUNT_N DESC
LIMIT 1;


SELECT GEO_NAME_SHORT, DIME_TIME, DIM_SEX, AMOUNT_N
FROM life_exp
WHERE GEO_NAME_SHORT = (
    SELECT GEO_NAME_SHORT
    FROM life_exp
    GROUP BY GEO_NAME_SHORT
    ORDER BY AVG(AMOUNT_N) DESC
    LIMIT 1
)
ORDER BY amount_n ASC
LIMIT 1;


